name: "Argon Security"
description: "Runs argon checks on changes in PR"
author: "Argon"
branding:
  icon: "shield"
  color: "purple"
inputs:
  argon-token:
    description: "Token provided by argon. This is sensitive, add this as a secret"
    required: true
  scanners:
    description: "Multiline list of checks to run. Defaults to all"
    required: false
  audit-only:
    description: "If true the action will never fail the workflow. Defaults to false"
    required: false
    default: "false"
  should-notify:
    description: "If true a notification will be sent to the configured Slack/Teams channel. Defaults to false"
    required: false
    default: "false"
  should-comment:
    description: "If true argon will make comments on the pull request for each finding. Defaults to true"
    required: false
    default: "true"

runs:
  using: "docker"
  image: "docker://argonsecurity/scanner:github"
